name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-repo:latest

      - name: Deploy to your server (optional)
        run: |
          ssh your-user@your-server "docker pull your-dockerhub-username/your-repo:latest && docker-compose up -d"
